"""test migration 2

Revision ID: 89ab840f4ae6
Revises: ad49c43ef499
Create Date: 2026-08-24 14:50:23.505517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89ab840f4ae6'
down_revision: Union[str, Sequence[str], None] = 'ad49c43ef499'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_task_history_id'), 'task_history', ['id'], unique=False)
    op.drop_constraint(op.f('fk_task_history_task'), 'task_history', type_='foreignkey')
    op.create_foreign_key(None, 'task_history', 'tasks', ['task_id'], ['id'])
    op.add_column('tasks', sa.Column('migration_test', sa.String(), nullable=True))
    op.drop_constraint(op.f('chk_tasks_priority'), 'tasks', type_='check')
    op.drop_constraint(op.f('chk_tasks_status'), 'tasks', type_='check')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(op.f('chk_tasks_status'), 'tasks', "status::text = ANY (ARRAY['TODO'::character varying, 'IN_PROGRESS'::character varying, 'DONE'::character varying, 'CANCELLED'::character varying]::text[])")
    op.create_check_constraint(op.f('chk_tasks_priority'), 'tasks', "priority::text = ANY (ARRAY['LOW'::character varying, 'MEDIUM'::character varying, 'HIGH'::character varying]::text[])")
    op.drop_column('tasks', 'migration_test')
    op.drop_constraint(None, 'task_history', type_='foreignkey')
    op.create_foreign_key(op.f('fk_task_history_task'), 'task_history', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_task_history_id'), table_name='task_history')
    # ### end Alembic commands ###
